print("Hello Avanish")
print("Kya haal chal hai bhai")
a=int(input())
b=int(input())
print("sum is ",(a+b))
print("Hey I have now pushed the code to github")
print("Checking after deleting the master branch")